// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArNIf5-P--IqJUkG809OBuhIXKCGDjMAg',
    appId: '1:1046045190563:web:0c4ea2aae957d7ebbb5216',
    messagingSenderId: '1046045190563',
    projectId: 'pet-care-app-07d',
    authDomain: 'pet-care-app-07d.firebaseapp.com',
    storageBucket: 'pet-care-app-07d.firebasestorage.app',
    measurementId: 'G-65JGLX2BXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKGgmmDtDdj0NjCS9OER4uRTnIhoblsTM',
    appId: '1:1046045190563:android:0d3fc3750cf1020abb5216',
    messagingSenderId: '1046045190563',
    projectId: 'pet-care-app-07d',
    storageBucket: 'pet-care-app-07d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtSLoy_7K1JbMQ7eFgOzfruICyDkTgNto',
    appId: '1:1046045190563:ios:8950304371df3c6cbb5216',
    messagingSenderId: '1046045190563',
    projectId: 'pet-care-app-07d',
    storageBucket: 'pet-care-app-07d.firebasestorage.app',
    iosBundleId: 'com.example.petCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArNIf5-P--IqJUkG809OBuhIXKCGDjMAg',
    appId: '1:1046045190563:web:cef6ab4729541d67bb5216',
    messagingSenderId: '1046045190563',
    projectId: 'pet-care-app-07d',
    authDomain: 'pet-care-app-07d.firebaseapp.com',
    storageBucket: 'pet-care-app-07d.firebasestorage.app',
    measurementId: 'G-EVV6YMXCT2',
  );
}
